config/routes.rb
Cerama::Application.routes.draw do


  get "orders/index"
  post "orders/create"

  get 'catalogue/:category_slug', to: 'catalogue#category', as: 'category'
  get 'catalogue/:category_slug/:product_id', to: 'catalogue#product', as: 'category_product'

  get 'pages/:page_slug', to: 'pages#show', as: 'page'

  get 'news', to: 'pages#news', as: 'news'
  get 'news/:news_item_id', to: 'pages#news_item' , as: 'news_item'

  root :to => 'pages#index'


  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :products
  has_many :product_groups
  attr_accessible :name, :order, :slug, :default_name, :show_on_main
end

app/models/news_item.rb
class NewsItem < ActiveRecord::Base
  attr_accessible :link, :show_on_main, :title, :text, :promo, :promo_url
  has_attached_file :promo, :styles => { :full_width => "980x300#", :large => "600x300>", :thumb => "50x50#" },
    :url => "/assets/:id/:style/:basename.:extension",
    :path => ":rails_root/public/assets/:id/:style/:basename.:extension"
end

app/models/order.rb
class Order < ActiveRecord::Base
  has_and_belongs_to_many :products
  attr_accessible :email, :name, :phone, :product_ids

  # accepts_nested_attributes_for :products, allow_destroy: false
end

app/models/page.rb
class Page < ActiveRecord::Base
  attr_accessible :slug, :text, :title
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_and_belongs_to_many :orders

  has_many :product_images
  belongs_to :category
  attr_accessible :description, :name, :show_on_main, :price_from_warehouse, :price_when_ordering, :quantity_in_stock, :sku, :product_images_attributes, :category_id
  accepts_nested_attributes_for :product_images, allow_destroy: true

  def name_with_default
    n = read_attribute(:name)
    n = self.category.andand.default_name if n.nil? or n.empty?
    n
  end
end

app/models/product_group.rb
class ProductGroup < ActiveRecord::Base
  belongs_to :category
  has_many :product_images
  attr_accessible :description, :name, :price_from_warehouse, :price_when_ordering, :quantity_in_stock, :show_on_main, :category_id, :product_images_attributes
  accepts_nested_attributes_for :product_images, allow_destroy: true
end

app/models/product_image.rb
class ProductImage < ActiveRecord::Base
  belongs_to :product
  attr_accessible :order, :image, :product_id, :image_url
  has_attached_file :image, :styles => { :full_width => "940x900>", :large => "600x400>", :medium => "220x200#", :thumb => "50x50#" },
    :url => "/assets/:id/:style/:basename.:extension",
    :path => ":rails_root/public/assets/:id/:style/:basename.:extension"
end

app/models/settings.rb
class Settings < ActiveRecord::Base
  class << self
    attr_accessor :store_attrs, :fake
  end 

  @store_attrs = [ :name, :phone1, :contacts, :email ]
  attr_accessible :data, :name, :phone1, :contacts, :email


  store :data, accessors: @store_attrs, coder: JSON
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :set_layout_variables
  def set_layout_variables
    @catalogue_categories = Category.where(show_on_main: true)
    @settings = Settings.first
  end
end

app/controllers/catalogue_controller.rb
class CatalogueController < ApplicationController
  def category
    @category = Category.find_by_slug(params[:category_slug])
  end

  def product
    # @category = Category.find(params[:category_id])
    @product = Product.find(params[:product_id])
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def index

  end

  def create
    #create
    @order = Order.create(params[:order])
    
    respond_to do |format|
      if @order.save
        OrderMailer.order_notification(@order).deliver
        format.json { render :json => @order }
      else
        format.json { render :json => @order.errors }
      end
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def show
    @page = Page.find_by_slug!(params[:page_slug])
  end

  def index
    @news = NewsItem.where(show_on_main: true)
    @products = Product.where(show_on_main: true)
  end
  
  def news
    @news = NewsItem.all() 
  end

  def news_item
    @news_item = NewsItem.find(params[:news_item_id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/catalogue_helper.rb
module CatalogueHelper
  def category_path(c)
    if c.respond_to? 'slug'
      super c.slug
    else
      super c
    end
  end
  
  def product_path(p)
    if p.category
      category_product_path(p.category.slug, p) 
    else
      super p
    end
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
  def news_item_path(news_item)
    if !news_item.link.strip().empty?
      news_item.link
    elsif !news_item.text.empty?
      super news_item
    else 
      ''
    end
  end
end

app/views/catalogue/_order_form.html.haml
.hidden
  
  =form_tag '/orders/create', { id: 'order-create', method: 'POST' } do |f|
    .t1
      -# %h3 Данные для заказа
      %h3 Как с Вами связаться?
      %label 
        %span Имя
        =text_field_tag "order[name]".to_sym, nil, placeholder: 'Иван Иванов'

      %label 
        %span Телефон
        =text_field_tag "order[phone]".to_sym, nil, placeholder: '+7 999 111 22 33'
      
      %label 
        %span E-mail
        =email_field_tag "order[email]".to_sym, nil, placeholder: 'ivan-ivanov@mail.ru'
      
    .t2
      -# .product-to-order
      -#   =hidden_field_tag "order[product_ids][]".to_sym, @product.id
      -#   %h4= "#{ @product.name_with_default } #{ @product.sku }"
      -#   - if @product.product_images[0]
      -#     =image_tag @product.product_images[0].image.url(:medium)


    .clear 
    =submit_tag "Отправить", class: 'red-button submit'
    -# =submit_tag "Отправить заказ", class: 'red-button submit'
    %span.errors

     

app/views/catalogue/category.html.haml
.row.products
  - unless @category.products.empty?
    - @category.products.each do |p|
      .span3
        .product
          .img
            - if p.product_images.first
              =link_to image_tag(p.product_images.first.image.url(:medium)), product_path(p) 

          %h4.name
            =link_to "#{ p.name_with_default } #{ p.sku }", product_path(p)
          
          %span.price-for-order
            %strong=number_to_currency p.price_when_ordering
            срок поставки 60 дней

          
          %a.red-button.order(href="#order-create") Заказать


          - if p.quantity_in_stock && p.quantity_in_stock > 0
            %span.price-from-warehouse
              %strong=number_to_currency p.price_from_warehouse
              со склада в Ростове
              %br
              (в наличии 
              %b= p.quantity_in_stock
              шт.)
         
  - else
    .empty
      В категории
      ="\"#{ @category.name }\""
      пока нет товаров.
      %br
      Расскажите нашим менеджерам по тел.
      =@settings.phone1
      %br
      о том, что вы искали и узнайте сроки поставки
      

app/views/catalogue/product.html.haml
.row.product.full
  .span8.gallerie
    
    .row

      .large.span7
        - @product.product_images.each do |pi|
          %a{class: "image-#{ pi.id }", href:"#{ pi.image.url(:original) }"}
            =image_tag pi.image.url(:large)

      .small.span1
        - @product.product_images.each do |pi|
          %div{ data: { image:  "image-#{ pi.id}" }}
            =image_tag pi.image.url(:thumb)


  .span4
    %h3.name= "#{ @product.name_with_default } #{ @product.sku }"
    .description=raw @product.description
    
    .price-for-order
      %strong=number_to_currency @product.price_when_ordering
      под заказ; срок поставки 60 дней
      
      %a.red-button.order(href="#order-create") Заказать


    - if @product.quantity_in_stock and @product.quantity_in_stock > 0
      .price-from-warehouse
        %strong=number_to_currency @product.price_from_warehouse
        со склада в Ростове (в наличии 
        = @product.quantity_in_stock
        шт.)
         

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title HOST
    = stylesheet_link_tag    'http://fonts.googleapis.com/css?family=Roboto+Slab:700,400&subset=latin,cyrillic'
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags

  %body
    .bg
      .container
        .page-header
          .c
            %h1
              =link_to_unless_current @settings.name, root_path

            .phone
              =@settings.phone1
              %a.red-button.order(href="#order-create") Заказать звонок
              .bottom
                звонок по России бесплатный


            %ul.nav
              -# %li=link_to_unless_current 'О компании', page_path('about')
              -# %li=link_to_unless_current 'Фабрики-партнеры', page_path('partners')
              -# %li=link_to_unless_current 'Оплата и доставка', page_path('delivery-payment')
              %li=link_to_unless_current 'Дилерам', page_path('for-dealer')
              %li=link_to_unless_current 'Контакты', page_path('contacts')

          .categories
            .row
              - g = @catalogue_categories.in_groups(3, false)
              - g.each_with_index do |group, i|

                .span4{ class: ''  }
                  - group.each do |category|
                    .item{ class:category.slug }
                      = link_to_unless_current raw("<span class='icon'></span><span class='name'>#{ category.name }</span>"), category_path(category) do
                        %span.icon
                        %span.name.current= category.name

        
        = render "catalogue/order_form" 

        %div(class="#{ controller.controller_name }-#{ controller.action_name } content-block")
          = yield


        .page-footer
          -# %h3 Контактная информация
          -# .text
            г.Ростов-на-Дону, ул. Малюгиной 232.

            %h4 Время работы
            9.00 до 18.00

            %h4 Телефоны
            8-800-500-20-62 (звонок по России бесплатный)
            %br
            +7(863) 229-86-92.



          -# .map
            .b
              :plain
                <script type="text/javascript" charset="utf-8" src="//api-maps.yandex.ru/services/constructor/1.0/js/?sid=XUjZto6vwBDDzUncAnuhaXfev8SehNNX&width=500&height=450"></script>
            %a.open-all(href="//maps.yandex.ru/?text=%D0%A0%D0%BE%D1%81%D1%81%D0%B8%D1%8F%2C%20%D0%A0%D0%BE%D1%81%D1%82%D0%BE%D0%B2-%D0%BD%D0%B0-%D0%94%D0%BE%D0%BD%D1%83%2C%20%D1%83%D0%BB%D0%B8%D1%86%D0%B0%20%D0%9C%D0%B0%D0%BB%D1%8E%D0%B3%D0%B8%D0%BD%D0%BE%D0%B9%2C%20226" target="_blank")Открыть на Яндекс.Картах &rarr; 

          .footer
            .contacts
              %a(href="/pages/contacts" target="_blank")
                =@settings.contacts 

    :plain
      <!-- Yandex.Metrika counter -->
      <script type="text/javascript">
      (function (d, w, c) {
          (w[c] = w[c] || []).push(function() {
              try {
                  w.yaCounter22985410 = new Ya.Metrika({id:22985410,
                          webvisor:true,
                          clickmap:true,
                          trackLinks:true,
                          accurateTrackBounce:true});
              } catch(e) { }
          });

          var n = d.getElementsByTagName("script")[0],
              s = d.createElement("script"),
              f = function () { n.parentNode.insertBefore(s, n); };
          s.type = "text/javascript";
          s.async = true;
          s.src = (d.location.protocol == "https:" ? "https:" : "http:") + "//mc.yandex.ru/metrika/watch.js";

          if (w.opera == "[object Opera]") {
              d.addEventListener("DOMContentLoaded", f, false);
          } else { f(); }
      })(document, window, "yandex_metrika_callbacks");
      </script>
      <noscript><div><img src="//mc.yandex.ru/watch/22985410" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
      <!-- /Yandex.Metrika counter -->

app/views/orders/create.html.erb
<h1>Orders#create</h1>
<p>Find me in app/views/orders/create.html.erb</p>

app/views/orders/index.html.erb
<h1>Orders#index</h1>
<p>Find me in app/views/orders/index.html.erb</p>

app/views/pages/_news_item_promo.haml
.news-item.item
  =link_to_unless news_item_path(n).empty?, image_tag(n.promo.url(:full_width)) + raw("<h2>#{ n.title }</h2>"), n

app/views/pages/index.html.haml
.slideshow
  - @news.each do |n|
    =render :partial => "news_item_promo", :locals => { :n => n }

  .slidesjs-previous.slidesjs-navigation.left.icon-circle-arrow-left.icon-4x
  .slidesjs-next.slidesjs-navigation.right.icon-circle-arrow-right.icon-4x

=link_to news_path, class: 'open-all'  do
  Все новости &rarr;

.row.promo
  - @products.each do |p|

    =link_to product_path(p) do
      .item
        - if p.product_images.first
          =image_tag(p.product_images.first.image.url(:full_width)) 
        %h2
          =raw strip_tags(p.description)
          %br
          %strong= number_to_currency p.price_when_ordering

=link_to category_path('sets'), class: 'open-all'  do
  Все кабинеты &rarr;

app/views/pages/news.haml
- @news.each do |n|
  =render :partial => "news_item_promo", :locals => { :n => n }

app/views/pages/news_item.haml
%h2=@news_item.title

.content
  = raw @news_item.text

app/views/pages/show.haml
%h2=@page.title

.content
  = raw @page.text